Add files via upload

diff --git a/M/conexao b/M/conexao
--- a/M/conexao
+++ b/M/conexao
@@ -1187,7 +1187,7 @@ echo "Execulte como root"
 						fun_openvpn
 					fi
 					;;
-				0)
+				00)
 					fun_conexao
 					;;
 				*)
@@ -1466,16 +1466,23 @@ exit 0' >$RCLOCAL
 		[[ $(netstat -nplt | grep -wc 'python') != '0' ]] && {
 			sks='\033[1;32mON'
 			echo -e "\033[0;34m╼ \033[1;32mPORTAS\033[1;37m: \033[1;37m$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)"
+		}
+		
+		[[ $(netstat -nplt | grep -wc 'novoWS') != '0' ]] && {
+			sks='\033[1;32mON'
+			echo -e "\033[0;34m╼ \033[1;32mPORTAS\033[1;37m: \033[1;37m$(netstat -nplt | grep 'novoWS' | awk {'print $4'} | cut -d: -f2 | xargs)"
 		} || {
 			sks='\033[1;31mOFF'
 		}
 		[[ $(screen -list | grep -wc 'proxy') != '0' ]] && var_sks1="\033[1;32m✓" || var_sks1="\033[1;31m✕"
 		[[ $(screen -list | grep -wc 'ws') != '0' ]] && var_sks2="\033[1;32m✓" || var_sks2="\033[1;31m✕"
+		[[ $(screen -list | grep -wc 'novoWS') != '0' ]] && var_sks3="\033[1;32m✓" || var_sks3="\033[1;31m✕"
 		[[ $(screen -list | grep -wc 'openpy') != '0' ]] && sksop="\033[1;32m✓" || sksop="\033[1;31m✕"
+		
 		echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
 		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m01\E[38;5;196m|\033[1;37m➜ \E[38;5;15mSOCKS SSH $var_sks1 \033[0m                       \033[0;34m┃"
 		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m02\E[38;5;196m|\033[1;37m➜ \E[38;5;15mWEBSOCKET $var_sks2 \033[0m                       \033[0;34m┃"
-		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m03\E[38;5;196m|\033[1;37m➜ \E[38;5;15mWEBSOCKET SECURITY \033[0m                \033[0;34m┃"
+		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m03\E[38;5;196m|\033[1;37m➜ \E[38;5;15mWEBSOCKET SECURITY $var_sks3 \033[0m              \033[0;34m┃"
 		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m04\E[38;5;196m|\033[1;37m➜ \E[38;5;15mSOCKS OPENVPN $sksop \033[0m                   \033[0;34m┃"
 		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m05\E[38;5;196m|\033[1;37m➜ \E[38;5;15mABRIR PORTA\033[0m                        \033[0;34m┃"
 		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m06\E[38;5;196m|\033[1;37m➜ \E[38;5;15mALTERAR STATUS SOCKS SSH\033[0m           \033[0;34m┃"
@@ -1537,6 +1544,8 @@ exit 0' >$RCLOCAL
 				sleep 3
 				fun_socks
 			fi
+
+
 		elif [[ "$resposta" = '2' ]]; then
 		clear
 			if ps x | grep -w wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
@@ -1562,7 +1571,7 @@ exit 0' >$RCLOCAL
 			else
 		echo -e "\E[44;1;37m             WEBSOCKET              \E[0m"
 				echo ""
-				read -p "$(echo -e "\033[1;32mQUAL PORTA DESEJA UTILIZAR? \033[1;37m")" -e -i 80 porta
+				read -p "$(echo -e "\033[1;32mQUAL PORTA DESEJA UTILIZAR? \033[1;37m")" -e -i 8080 porta
 				[[ -z "$porta" ]] && {
 					echo ""
 					echo -e "\033[1;31mPorta invalida!"
@@ -1589,10 +1598,15 @@ exit 0' >$RCLOCAL
 				
 				fun_socks
 			fi
-		elif [[ "$resposta" = '3' ]]; then
+
+
+
+
+elif [[ "$resposta" = '99' ]]; then
 		clear
 		if ps x | grep -w WebSocket | grep -v grep 1>/dev/null 2>/dev/null; then
-		echo -e "\E[41;1;37m          WEBSOCKET SECURITY              \E[0m"
+		figlet 'SCOTT-PRO' | lolcat
+		echo -e "\E[41;1;37m       🚀   WEBSOCKET SECURITY   🚀           \E[0m"
 				echo ""
 				fun_wsswsocksoff() { 
 					pkill WebSocket
@@ -1613,7 +1627,8 @@ exit 0' >$RCLOCAL
 				
 				fun_socks
 			else
-		echo -e "\E[44;1;37m          WEBSOCKET SECURITY              \E[0m"
+			figlet 'MODDDERAJUDA' | lolcat
+		echo -e "\E[44;1;37m       🚀   WEBSOCKET SECURITY   🚀           \E[0m"
 				echo ""
 				echo "$(echo -e "\033[1;32mPORTA UTILIZADA 80 \033[1;37m")"
 				[[ -z "porta" ]] && {
@@ -1642,6 +1657,73 @@ exit 0' >$RCLOCAL
 				
 				fun_socks
 			fi
+
+
+
+elif [[ "$resposta" = '3' ]]; then
+		clear
+		if ps x | grep -w WebSocket | grep -v grep 1>/dev/null 2>/dev/null; then
+		figlet 'MODDDERAJUDA' | lolcat
+		echo -e "\E[41;1;37m         WEBSOCKET SECURITY              \E[0m"
+				echo ""
+				fun_wsswsocksoff() { 
+					pkill WebSocket
+					for pidproxy in $(screen -ls | grep ".ws" | awk {'print $1'}); do
+						screen -r -S "$WebSocket" -X quit
+					done
+					[[ $(grep -wc "WebSocket" /etc/autostart) != '0' ]] && {
+						sed -i '/WebSocket/d' /etc/autostart
+					}
+					sleep 1
+					screen -wipe >/dev/null
+				}
+				echo -e "\033[1;32mDESATIVANDO O WEBSOCKET SECURITY\033[1;33m"
+				echo ""
+				fun_bar 'fun_wsswsocksoff'
+				echo ""
+				echo -e "\033[1;32mWEBSOCKET SECURITY DESATIVADO COM SUCESSO!\033[1;33m"
+				
+				fun_socks
+			else
+			figlet 'MODDDERAJUDA' | lolcat
+		echo -e "\E[44;1;37m          WEBSOCKET SECURITY             \E[0m"
+				echo ""
+				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR ? \033[1;33mEXEMPLO : 80 ou 8080\033[1;37m: "
+				read -p '★ Digite a porta: ' porta
+				[[ -z $porta ]] && {
+					echo ""
+					echo -e "\033[1;31mPorta invalida!"
+					
+				fun_socks
+				}
+				verif_ptrs $porta
+				fun_iniwssocks() {
+					sleep 1
+					screen -dmS novoWS /etc/SSHPlus/WebSocket
+					[[ $(grep -wc "WebSocket" /etc/autostart) = '0' ]] && {
+						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS novoWS $porta /etc/SSHPlus/WebSocket $porta; }" >>/etc/autostart
+					} || {
+						sed -i '/wsproxy.py/d' /etc/autostart
+						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS novoWS $porta /etc/SSHPlus/WebSocket $porta; }" >>/etc/autostart
+					}
+				}
+				echo ""
+				echo -e "\033[1;32mINICIANDO O WEBSOCKET SECURITY\033[1;33m"
+				echo ""
+				fun_bar 'fun_iniwssocks'
+				echo ""
+				echo -e "\033[1;32m Websocket security ativado com sucesso! ;)\033[1;33m"
+				sleep 3
+				fun_socks
+			fi
+
+
+
+
+
+
+
+
 
 
 		elif [[ "$resposta" = '4' ]]; then
@@ -1701,6 +1783,8 @@ exit 0' >$RCLOCAL
 				sleep 3
 				fun_socks
 			fi
+
+
 		elif [[ "$resposta" = '5' ]]; then
 			if ps x | grep proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
 				sockspt=$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)
@@ -2084,6 +2168,16 @@ echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━�
 			} || {
 				sts5="\033[1;31m✕ "
 			}
+			
+		
+			[[ "$(netstat -tlpn | grep 'WebSocket' | wc -l)" != '0' ]] && {
+				echo -e "\033[01;31m\033[1;32mSERVICO: \033[1;33mWEBSOCKET SECURITY \033[1;32mPORTA: \033[1;37m80\033[01;31m                       \033[0m"
+				sts4="\033[1;32m✓ "
+			} || {
+				sts4="\033[1;31m✕ "
+			}
+			
+			
 
 			[[ "$(netstat -tlpn | grep 'python' | wc -l)" != '0' ]] && {
 				echo -e "\033[1;32mPROXY SOCKS\033[1;31m: \033[1;37m$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)"
