Update conexao

diff --git a/M/conexao b/M/conexao
--- a/M/conexao
+++ b/M/conexao
@@ -1461,25 +1461,35 @@ exit 0' >$RCLOCAL
 	fun_socks() {
 		clear
 			echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
-			echo -e "\033[0;34m┃\E[44;1;37m          GERENCIAR PROXY SOCKS          \E[0m\033[0;34m┃"
-			echo -e "\033[0;34m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m"
-	[[ $(netstat -nplt | grep -wc 'security') != '0' ]] && {
-    porta_security=$(netstat -nplt | grep -w 'security' | awk '{split($4,a,":"); print a[length(a)]}')
-    sks='\033[1;32mON'
-    echo -e "\033[1;32mPORTAS (security)\033[1;31m: \033[1;37m$porta_security"
-    }
-    
-    [[ $(netstat -nplt | grep -wc 'proxydt') != '0' ]] && {
-    porta_proxydt=$(netstat -nplt | grep -w 'proxydt' | awk '{split($4,a,":"); print a[length(a)]}')
-    sks='\033[1;32mON'
-    echo -e "\033[1;32mPORTAS (proxydt)\033[1;31m: \033[1;37m$porta_proxydt"
-    }
-    
-    [[ $(netstat -nplt | grep -wc 'python') != '0' ]] && {
-    porta_python=$(netstat -nplt | grep -w 'python' | awk '{split($4,a,":"); print a[length(a)]}')
+echo -e "\033[0;34m┃\E[44;1;37m          GERENCIAR PROXY SOCKS          \E[0m\033[0;34m┃"
+echo -e "\033[0;34m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m"
+
+
+
+[[ "$(ss -tlpn | grep 'security' | wc -l)" != '0' ]] && {
+    porta=$(ss -nplt | grep -w 'security' | awk '{print $4}' | cut -d: -f2 | uniq)
+    echo -e "\033[1;32mWEBSOCKET SECURITY\033[1;31m: \033[1;37m$porta"
+    sts4="\033[1;32m✓ "
+}
+
+
+[[ "$(netstat -tlpn | grep 'proxydt' | wc -l)" != '0' ]] && {
+    echo -e "\033[1;32mPROXY DT\033[1;31m: \033[1;37m$(netstat -nplt | grep 'proxydt' | awk '{print $4}' | cut -d: -f2)"
+    sts4="\033[1;32m✓ "
+}
+
+
+
+
+
+
+[[ $(netstat -nplt | grep -wc 'python') != '0' ]] && {
+    porta_python=$(netstat -nplt | grep -w 'python' | awk '{print $4}' | cut -d: -f2)
     sks='\033[1;32mON'
     echo -e "\033[1;32mPORTAS (python)\033[1;31m: \033[1;37m$porta_python"
-    }
+}
+
+
 		
 		[[ $(screen -list | grep -wc 'proxy') != '0' ]] && var_sks1="\033[1;32m✓" || var_sks1="\033[1;31m✕"
 		[[ $(screen -list | grep -wc 'ws') != '0' ]] && var_sks2="\033[1;32m✓" || var_sks2="\033[1;31m✕"
@@ -1676,6 +1686,20 @@ elif [[ "$resposta" = '300' ]]; then
 
 
 
+
+
+
+
+
+
+
+
+
+
+
+
+
+
 elif [[ "$resposta" = '3' ]]; then
     clear
     if ps x | grep -w security | grep -v grep 1>/dev/null 2>/dev/null; then
@@ -1714,15 +1738,17 @@ elif [[ "$resposta" = '3' ]]; then
         }
         verif_ptrs $portaws
         fun_inisecurity() {
-            sleep 1
-            screen -dmS security /etc/SSHPlus/security -proxy_port 0.0.0.0:$portaws -msg=SECURITY
-            [[ $(grep -wc "security" /etc/autostart) = '0' ]] && {
-                echo -e "netstat -tlpn | grep -w $portaws > /dev/null || {  screen -r -S 'security' -X quit;  screen -dmS security /etc/SSHPlus/security -proxy_port 0.0.0.0:$portaws -msg=SECURITY; }" >>/etc/autostart
-            } || {
-                sed -i '/security/d' /etc/autostart
-                echo -e "netstat -tlpn | grep -w $portaws > /dev/null || {  screen -r -S 'security' -X quit;  screen -dmS security /etc/SSHPlus/security -proxy_port 0.0.0.0:$portaws -msg=SECURITY; }" >>/etc/autostart
-            }
-        }
+    sleep 1
+    screen -dmS security /etc/SSHPlus/security -proxy_port 0.0.0.0:$portaws -msg=SECURITY
+    [[ $(grep -wc "security" /etc/autostart) = '0' ]] && {
+        echo -e "netstat -tlpn | grep -w $portaws > /dev/null || {  screen -r -S 'security' -X quit;  screen -dmS security /etc/SSHPlus/security -proxy_port 0.0.0.0:$portaws -msg=SECURITY; }" >>/etc/autostart
+    } || {
+        sed -i '/security/d' /etc/autostart
+        echo -e "netstat -tlpn | grep -w $portaws > /dev/null || {  screen -r -S 'security' -X quit;  screen -dmS security /etc/SSHPlus/security -proxy_port 0.0.0.0:$portaws -msg=SECURITY; }" >>/etc/autostart
+    }
+    # Adicione o comando para exibir a porta ativa
+    echo -e "\033[1;32mWEBSOCKET SECURITY ATIVADO NA PORTA:\033[1;37m $portaws"
+}
         echo ""
         echo -e "\033[1;32mINICIANDO WEBSOCKET SECURITY\033[1;33m"
         echo ""
@@ -1732,6 +1758,69 @@ elif [[ "$resposta" = '3' ]]; then
         
         fun_socks
     fi
+
+
+
+
+
+elif [[ "$resposta" = '99' ]]; then
+    clear
+    if ps x | grep -w wssecurity | grep -v grep 1>/dev/null 2>/dev/null; then
+        echo -e "\E[41;1;37m             SECURITY               \E[0m"
+        echo ""
+        fun_wssecurityoff() {
+            for pidproxy in $(screen -ls | grep ".wssecurity" | awk {'print $1'}); do
+                screen -r -S "$pidproxy" -X quit
+            done
+            [[ $(grep -wc "wssecurity" /etc/autostart) != '0' ]] && {
+                sed -i '/wssecurity/d' /etc/autostart
+            }
+            sleep 1
+            screen -wipe >/dev/null
+        }
+        echo -e "\033[1;32mDESATIVANDO O SECURITY\033[1;33m"
+        echo ""
+        fun_bar 'fun_wssecurityoff'
+        echo ""
+        echo -e "\033[1;32mSECURITY DESATIVADO COM SUCESSO!\033[1;33m"
+        
+        fun_socks
+    else
+        echo -e "\E[44;1;37m             PROXY DT               \E[0m"
+        echo ""
+        echo -e "\033[1;32mQUAL PORTA DESEJA ULTILIZAR ? \033"
+        echo ""
+        echo -e "\033[1;32mEXEMPLO :\033[1;33m80 ou 8080\033"
+        echo ""
+        read -p "$(echo -e "\033[1;32mQUAL PORTA DESEJA UTILIZAR? \033[1;37m: ")" porta
+        [[ -z "$portaws" ]] && {
+            echo ""
+            echo -e "\033[1;31mPorta invalida!"
+            
+            fun_socks
+        }
+        verif_ptrs $portaws
+        fun_iniwssecurity() {
+            sleep 1
+            screen -dmS wssecurity /etc/SSHPlus/wssecurity -proxy_port 0.0.0.0:$portaws -msg=SECURITY
+            [[ $(grep -wc "wssecurity" /etc/autostart) = '0' ]] && {
+                echo -e "netstat -tlpn | grep -w $portaws > /dev/null || {  screen -r -S 'wssecurity' -X quit;  screen -dmS wssecurity /etc/SSHPlus/wssecurity -proxy_port 0.0.0.0:$portaws -msg=SECURITY; }" >>/etc/autostart
+            } || {
+                sed -i '/wssecurity/d' /etc/autostart
+                echo -e "netstat -tlpn | grep -w $portaws > /dev/null || {  screen -r -S 'wssecurity' -X quit;  screen -dmS wssecurity /etc/SSHPlus/wssecurity -proxy_port 0.0.0.0:$portaws -msg=SECURITY; }" >>/etc/autostart
+            }
+        }
+        echo ""
+        echo -e "\033[1;32mINICIANDO O WEBSOCKET SECURITY\033[1;33m"
+        echo ""
+        fun_bar 'fun_iniwssecurity'
+        echo ""
+        echo -e "\033[1;32SECURITY ATIVADO COM SUCESSO\033[1;33m"
+        
+        fun_socks
+    fi
+
+
 
 
 
@@ -2240,19 +2329,22 @@ echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━�
 			}
 			
 			[[ "$(netstat -tlpn | grep 'WebSocket' | wc -l)" != '0' ]] && {
-				echo -e "\033[1;32mWEBSOCKET SECURITY\033[1;33m ATIVADO!\033[1;37m$(netstat -nplt | grep 'WebSocket' | awk {'print $4'} | cut -d: -f2 | xargs)"
+				echo -e "\033[1;32mWEBSOCKET\033[1;33m ATIVADO!\033[1;37m$(netstat -nplt | grep 'WebSocket' | awk {'print $4'} | cut -d: -f2 | xargs)"
 				sts4="\033[1;32m✓ "
 			} || {
 				sts4="\033[1;31m✕ "
 			}
 			
+		
+			
 			[[ "$(netstat -tlpn | grep 'security' | wc -l)" != '0' ]] && {
-    porta_security=$(netstat -nplt | grep -w 'security' | awk '{split($4,a,":"); print a[length(a)]}')
-    echo -e "\033[1;32mWEBSOCKET SECURITY\033[1;31m: \033[1;37m$porta_security"
-    sts4="\033[1;32m✓ "
-} || {
-    sts4="\033[1;31m✕ "
-}
+			porta=$(ss -nplt | grep -w 'security' | awk '{print $4}' | cut -d: -f2 | uniq)
+				echo -e "\033[1;32mWEBSOCKET SECURITY\033[1;31m: \033[1;37m$porta"
+				sts4="\033[1;32m✓ "
+			} || {
+				sts4="\033[1;31m✕ "
+			}
+			
 			
 			[[ "$(netstat -tlpn | grep 'proxydt' | wc -l)" != '0' ]] && {
 				echo -e "\033[1;32mPROXY DT\033[1;31m: \033[1;37m$(netstat -nplt | grep 'proxydt' | awk {'print $4'} | cut -d: -f2 | xargs)"
