Add files via upload

diff --git a/M/conexao b/M/conexao
--- a/M/conexao
+++ b/M/conexao
@@ -1476,6 +1476,7 @@ exit 0' >$RCLOCAL
 		}
 		[[ $(screen -list | grep -wc 'proxy') != '0' ]] && var_sks1="\033[1;32m✓" || var_sks1="\033[1;31m✕"
 		[[ $(screen -list | grep -wc 'ws') != '0' ]] && var_sks2="\033[1;32m✓" || var_sks2="\033[1;31m✕"
+		[[ $(screen -list | grep -wc 'proxydt') != '0' ]] && var_sks4="\033[1;32m✓" || var_sks4="\033[1;31m✕"
 		[[ $(screen -list | grep -wc 'novoWS') != '0' ]] && var_sks3="\033[1;32m✓" || var_sks3="\033[1;31m✕"
 		[[ $(screen -list | grep -wc 'openpy') != '0' ]] && sksop="\033[1;32m✓" || sksop="\033[1;31m✕"
 		
@@ -1483,10 +1484,11 @@ exit 0' >$RCLOCAL
 		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m01\E[38;5;196m|\033[1;37m➜ \E[38;5;15mSOCKS SSH $var_sks1 \033[0m                       \033[0;34m┃"
 		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m02\E[38;5;196m|\033[1;37m➜ \E[38;5;15mWEBSOCKET $var_sks2 \033[0m                       \033[0;34m┃"
 		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m03\E[38;5;196m|\033[1;37m➜ \E[38;5;15mWEBSOCKET SECURITY $var_sks3 \033[0m              \033[0;34m┃"
-		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m04\E[38;5;196m|\033[1;37m➜ \E[38;5;15mSOCKS OPENVPN $sksop \033[0m                   \033[0;34m┃"
-		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m05\E[38;5;196m|\033[1;37m➜ \E[38;5;15mABRIR PORTA\033[0m                        \033[0;34m┃"
-		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m06\E[38;5;196m|\033[1;37m➜ \E[38;5;15mALTERAR STATUS SOCKS SSH\033[0m           \033[0;34m┃"
-		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m07\E[38;5;196m|\033[1;37m➜ \E[38;5;15mALTERAR STATUS WEBSOCKET\033[0m           \033[0;34m┃"
+		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m04\E[38;5;196m|\033[1;37m➜ \E[38;5;15mPROXY DT $var_sks4 \033[0m                        \033[0;34m┃"
+		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m05\E[38;5;196m|\033[1;37m➜ \E[38;5;15mSOCKS OPENVPN $sksop \033[0m                   \033[0;34m┃"
+		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m06\E[38;5;196m|\033[1;37m➜ \E[38;5;15mABRIR PORTA\033[0m                        \033[0;34m┃"
+		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m07\E[38;5;196m|\033[1;37m➜ \E[38;5;15mALTERAR STATUS SOCKS SSH\033[0m           \033[0;34m┃"
+		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m08\E[38;5;196m|\033[1;37m➜ \E[38;5;15mALTERAR STATUS WEBSOCKET\033[0m           \033[0;34m┃"
 		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m00\E[38;5;196m|\033[1;37m➜ \E[38;5;15mVOLTAR\033[0m                             \033[0;34m┃"
 		echo -e "\033[0;34m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m"
 		echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;37m?\033[1;31m?\033[1;37m : ";
@@ -1667,14 +1669,67 @@ elif [[ "$resposta" = '3' ]]; then
 
 
 
+elif [[ "$resposta" = '4' ]]; then
+    clear
+    if ps x | grep -w proxydt | grep -v grep 1>/dev/null 2>/dev/null; then
+        echo -e "\E[41;1;37m             PROXY DT               \E[0m"
+        echo ""
+        fun_proxydtoff() {
+            for pidproxy in $(screen -ls | grep ".proxydt" | awk {'print $1'}); do
+                screen -r -S "$pidproxy" -X quit
+            done
+            [[ $(grep -wc "proxydt" /etc/autostart) != '0' ]] && {
+                sed -i '/proxydt/d' /etc/autostart
+            }
+            sleep 1
+            screen -wipe >/dev/null
+        }
+        echo -e "\033[1;32mDESATIVANDO O PROXY DT\033[1;33m"
+        echo ""
+        fun_bar 'fun_proxydtoff'
+        echo ""
+        echo -e "\033[1;32mPROXY DT DESATIVADO COM SUCESSO!\033[1;33m"
+        
+        fun_socks
+    else
+        echo -e "\E[44;1;37m             PROXY DT               \E[0m"
+        echo ""
+        echo -e "\033[1;32mQUAL PORTA DESEJA ULTILIZAR ? \033"
+        echo ""
+        echo -e "\033[1;32mEXEMPLO :\033[1;33m80 ou 8080\033"
+        echo ""
+        read -p "$(echo -e "\033[1;32mQUAL PORTA DESEJA UTILIZAR? \033[1;37m: ")" porta
+        [[ -z "$porta" ]] && {
+            echo ""
+            echo -e "\033[1;31mPorta invalida!"
+            
+            fun_socks
+        }
+        verif_ptrs $porta
+        fun_iniproxydt() {
+            sleep 1
+            screen -dmS proxydt python /etc/SSHPlus/proxydt $porta
+            [[ $(grep -wc "proxydt" /etc/autostart) = '0' ]] && {
+                echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'proxydt' -X quit;  screen -dmS proxydt python /etc/SSHPlus/proxydt $porta; }" >>/etc/autostart
+            } || {
+                sed -i '/proxydt/d' /etc/autostart
+                echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'proxydt' -X quit;  screen -dmS proxydt python /etc/SSHPlus/proxydt $porta; }" >>/etc/autostart
+            }
+        }
+        echo ""
+        echo -e "\033[1;32mINICIANDO O PROXY DT\033[1;33m"
+        echo ""
+        fun_bar 'fun_iniproxydt'
+        echo ""
+        echo -e "\033[1;32PROXY DT ATIVADO COM SUCESSO\033[1;33m"
+        
+        fun_socks
+    fi
 
 
 
 
-
-
-
-		elif [[ "$resposta" = '4' ]]; then
+		elif [[ "$resposta" = '5' ]]; then
 			if ps x | grep -w open.py | grep -v grep 1>/dev/null 2>/dev/null; then
 		echo -e "\E[41;1;37m            SOCKS OPENVPN             \E[0m"
 				echo ""
@@ -1733,7 +1788,7 @@ elif [[ "$resposta" = '3' ]]; then
 			fi
 
 
-		elif [[ "$resposta" = '5' ]]; then
+		elif [[ "$resposta" = '6' ]]; then
 			if ps x | grep proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
 				sockspt=$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)
 		echo -e "\E[44;1;37m            PROXY SOCKS             \E[0m"
@@ -1767,7 +1822,7 @@ elif [[ "$resposta" = '3' ]]; then
 				sleep 2
 				fun_socks
 			fi
-		elif [[ "$resposta" = '6' ]]; then
+		elif [[ "$resposta" = '7' ]]; then
 			if ps x | grep -w proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
 		msgsocks=$(cat /etc/SSHPlus/proxy.py | grep -E "MSG =" | awk -F = '{print $2}' | cut -d "'" -f 2)
 				echo -e "\E[44;1;37m             PROXY SOCKS              \E[0m"
@@ -1860,7 +1915,7 @@ elif [[ "$resposta" = '3' ]]; then
 				sleep 2
 				fun_socks
 			fi
-		elif [[ "$resposta" = '7' ]]; then
+		elif [[ "$resposta" = '8' ]]; then
 			if ps x | grep -w wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
 		msgsocks=$(cat /etc/SSHPlus/wsproxy.py | grep -E "MSG =" | awk -F = '{print $2}' | cut -d "'" -f 2)
 				echo -e "\E[44;1;37m             WEBSOCKET              \E[0m"
@@ -2119,6 +2174,13 @@ echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━�
 			
 			[[ "$(netstat -tlpn | grep 'WebSocket' | wc -l)" != '0' ]] && {
 				echo -e "\033[1;32mWEBSOCKET SECURITY\033[1;33m ATIVADO!\033[1;37m$(netstat -nplt | grep 'WebSocket' | awk {'print $4'} | cut -d: -f2 | xargs)"
+				sts4="\033[1;32m✓ "
+			} || {
+				sts4="\033[1;31m✕ "
+			}
+			
+			[[ "$(netstat -tlpn | grep 'proxydt' | wc -l)" != '0' ]] && {
+				echo -e "\033[1;32mPROXY DT\033[1;33m ATIVADO!\033[1;37m$(netstat -nplt | grep 'proxydt' | awk {'print $4'} | cut -d: -f2 | xargs)"
 				sts4="\033[1;32m✓ "
 			} || {
 				sts4="\033[1;31m✕ "
