Update initcheck

diff --git a/M/initcheck b/M/initcheck
--- a/M/initcheck
+++ b/M/initcheck
@@ -46,9 +46,11 @@ fun_initcheck() {
     echo ""
     var_sks1=$(ps x | grep "checkuser" | grep -v grep >/dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
     var_sks2=$(ps x | grep "4gcheck" | grep -v grep >/dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
+    var_sks3=$(ps x | grep "5gcheck" | grep -v grep >/dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
     echo ""
     echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mATIVAR CHECKUSER(PADRÃO) $var_sks1 \033[0m"
     echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mATIVAR CHECKUSER(CONECTA4G) $var_sks2 \033[0m"
+    echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mATIVAR CHECKUSER(CONECTA5G MODDER) $var_sks3 \033[0m"
     echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR\033[0m"
     echo ""
     echo -ne "\033[1;32mO QUE DESEJA FAZER \033[1;33m?\033[1;37m "
@@ -199,6 +201,13 @@ fun_initcheck() {
             read x
             fun_initcheck
         fi
+        
+    elif [[ "$resposta" = '3' ]]; then
+        # Chamar o script checkuserMenu.sh
+        bash /root/checkuser/checkuserMenu.sh  # Substitua pelo caminho correto
+
+
+
     elif [[ "$resposta" = '0' ]]; then
         echo ""
         echo -e "\033[1;31mRetornando...\033[0m"
@@ -215,7 +224,7 @@ fun_initcheck() {
 inst_depedencias() {
     # ehck installed pip3
     if ! [ -x "$(command -v pip3)" ]; then
-        echo 'Error: pip3 nÃ£o estÃ¡ instalado.' >&2
+        echo 'Error: pip3 não está instalado.' >&2
         echo 'Instale pip3 e execute o script novamente.' >&2
 
         if ! apt-get install -y python3-pip; then
@@ -228,6 +237,9 @@ inst_depedencias() {
 
     # install flask
     pip3 install flask >/dev/null 2>&1
+    
+    # install python3
+    apt install python3
 
     # download check.py
     [[ -e "/etc/SSHPlus/check.py" ]] && {
@@ -254,7 +266,23 @@ inst_depedencias() {
         mv -f $HOME/check /bin/check
         chmod 777 /bin/check
     }
+    
+        [[ -e "/root/checkuser/checkuserMenu.sh" ]] && {
+        sleep 0.1
+    } || {
+        cd $HOME
+        sudo kill -9 $(lsof -t -i:5454)
+        pkill -9 -f "/root/checkuser/checkuser.py"
+        git clone https://github.com/modderajuda/checkuser.git
+chmod +x /root/checkuser/checkuserMenu.sh
+        mv -f $HOME/checkuserMenu.sh /root/checkuser/checkuserMenu.sh
+        chmod 777 /root/checkuser/checkuserMenu.sh
+    }
+    
+    
+    
 }
+
 
 [[ -e "/etc/SSHPlus/check.py" ]] && [[ -e "/etc/SSHPlus/4gcheck.py" ]] && [[ -e "/bin/check" ]] && {
     fun_initcheck
